-- Reconcile the Live Board schema with the shipped client contract.
--
-- live-board.html loads live-board-messages-v2.js, which calls three RPCs that
-- were never committed to migrations (get_live_board_messages,
-- post_live_board_message, clear_live_board_messages). The short-access shim
-- (live-board-short-access.js) also redirects every room creation to an
-- untracked create_live_board_room_v2 that accepts p_student_short_token, and
-- 20260728124500_student_workspace_live_board_sessions.sql already inserts
-- into live_board_rooms.student_short_token_hash — a column no migration
-- created. Compact student links (#j=ROOM.<16-char token>) require the room
-- read/update RPCs to accept the short-token hash as well.
--
-- This migration is idempotent: it drops and recreates the seven affected
-- functions (any signature) so it is safe to apply whether or not hand-applied
-- versions exist in production, and it uses IF NOT EXISTS guards for the
-- column/table/FK.

begin;

-- Drop every existing overload of the affected functions. PostgREST resolves
-- RPCs by name and cannot pick between overloads; dropping first also lets us
-- change return types if production drifted.
do $$
declare
  fn record;
begin
  for fn in
    select p.oid::regprocedure::text as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'create_live_board_room',
        'create_live_board_room_v2',
        'get_live_board_room',
        'update_live_board_student',
        'get_live_board_messages',
        'post_live_board_message',
        'clear_live_board_messages'
      )
  loop
    execute format('drop function %s', fn.signature);
  end loop;
end;
$$;

-- Short student token column -------------------------------------------------

alter table public.live_board_rooms
  add column if not exists student_short_token_hash text;

-- Session messages table -----------------------------------------------------

create table if not exists public.live_board_messages (
  id bigint generated always as identity primary key,
  room_code text not null,
  sender_role text not null check (sender_role in ('teacher', 'student')),
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

-- Defensive column adds in case a hand-applied table already exists.
alter table public.live_board_messages
  add column if not exists id bigint generated by default as identity;
alter table public.live_board_messages
  add column if not exists room_code text;
alter table public.live_board_messages
  add column if not exists sender_role text;
alter table public.live_board_messages
  add column if not exists body text;
alter table public.live_board_messages
  add column if not exists created_at timestamptz default now();

-- Messages die with their room: expiry sweeps and end_student_workspace_live_board
-- delete live_board_rooms rows, so the cascade removes their messages too.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'live_board_messages_room_code_fkey'
      and conrelid = 'public.live_board_messages'::regclass
  ) then
    alter table public.live_board_messages
      add constraint live_board_messages_room_code_fkey
      foreign key (room_code)
      references public.live_board_rooms(room_code)
      on delete cascade;
  end if;
end;
$$;

create index if not exists live_board_messages_room_idx
  on public.live_board_messages (room_code, created_at, id);

alter table public.live_board_messages enable row level security;
revoke all on table public.live_board_messages from anon, authenticated;

-- Room functions --------------------------------------------------------------

create function public.create_live_board_room(
  p_room_code text,
  p_teacher_token text,
  p_student_token text,
  p_fen text,
  p_pgn text default '',
  p_orientation text default 'white'
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_room public.live_board_rooms;
begin
  if p_room_code !~ '^[A-Z0-9]{6,12}$' then
    raise exception 'Invalid room code';
  end if;
  if length(p_teacher_token) < 32 or length(p_student_token) < 32 then
    raise exception 'Room tokens are too short';
  end if;
  if p_orientation not in ('white', 'black') then
    raise exception 'Invalid orientation';
  end if;

  delete from public.live_board_rooms where expires_at <= now();

  insert into public.live_board_rooms (
    room_code, teacher_token_hash, student_token_hash,
    student_short_token_hash, fen, pgn, orientation
  ) values (
    p_room_code,
    encode(extensions.digest(convert_to(p_teacher_token, 'UTF8'), 'sha256'), 'hex'),
    encode(extensions.digest(convert_to(p_student_token, 'UTF8'), 'sha256'), 'hex'),
    encode(extensions.digest(convert_to(left(p_student_token, 16), 'UTF8'), 'sha256'), 'hex'),
    p_fen,
    coalesce(p_pgn, ''),
    p_orientation
  )
  returning * into v_room;

  return jsonb_build_object(
    'room_code', v_room.room_code,
    'fen', v_room.fen,
    'pgn', v_room.pgn,
    'orientation', v_room.orientation,
    'last_move', v_room.last_move,
    'student_moves_allowed', v_room.student_moves_allowed,
    'revision', v_room.revision,
    'active_lesson_id', v_room.active_lesson_id,
    'expires_at', v_room.expires_at
  );
exception
  when unique_violation then
    raise exception 'Room code already exists';
end;
$$;

create function public.create_live_board_room_v2(
  p_room_code text,
  p_teacher_token text,
  p_student_token text,
  p_student_short_token text,
  p_fen text,
  p_pgn text default '',
  p_orientation text default 'white'
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_room public.live_board_rooms;
begin
  if p_room_code !~ '^[A-Z0-9]{6,12}$' then
    raise exception 'Invalid room code';
  end if;
  if length(p_teacher_token) < 32 or length(p_student_token) < 32 then
    raise exception 'Room tokens are too short';
  end if;
  if char_length(coalesce(p_student_short_token, '')) not between 8 and 64 then
    raise exception 'Invalid short student token';
  end if;
  if p_orientation not in ('white', 'black') then
    raise exception 'Invalid orientation';
  end if;

  delete from public.live_board_rooms where expires_at <= now();

  insert into public.live_board_rooms (
    room_code, teacher_token_hash, student_token_hash,
    student_short_token_hash, fen, pgn, orientation
  ) values (
    p_room_code,
    encode(extensions.digest(convert_to(p_teacher_token, 'UTF8'), 'sha256'), 'hex'),
    encode(extensions.digest(convert_to(p_student_token, 'UTF8'), 'sha256'), 'hex'),
    encode(extensions.digest(convert_to(p_student_short_token, 'UTF8'), 'sha256'), 'hex'),
    p_fen,
    coalesce(p_pgn, ''),
    p_orientation
  )
  returning * into v_room;

  return jsonb_build_object(
    'room_code', v_room.room_code,
    'fen', v_room.fen,
    'pgn', v_room.pgn,
    'orientation', v_room.orientation,
    'last_move', v_room.last_move,
    'student_moves_allowed', v_room.student_moves_allowed,
    'revision', v_room.revision,
    'active_lesson_id', v_room.active_lesson_id,
    'expires_at', v_room.expires_at
  );
exception
  when unique_violation then
    raise exception 'Room code already exists';
end;
$$;

create function public.get_live_board_room(
  p_room_code text,
  p_access_token text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
stable
as $$
declare
  v_room public.live_board_rooms;
  v_hash text;
begin
  v_hash := encode(extensions.digest(convert_to(coalesce(p_access_token, ''), 'UTF8'), 'sha256'), 'hex');

  select * into v_room
  from public.live_board_rooms
  where room_code = p_room_code
    and expires_at > now()
    and (teacher_token_hash = v_hash
         or student_token_hash = v_hash
         or student_short_token_hash = v_hash);

  if not found then
    raise exception 'Room not found or access token is invalid';
  end if;

  return jsonb_build_object(
    'room_code', v_room.room_code,
    'fen', v_room.fen,
    'pgn', v_room.pgn,
    'orientation', v_room.orientation,
    'last_move', v_room.last_move,
    'student_moves_allowed', v_room.student_moves_allowed,
    'revision', v_room.revision,
    'active_lesson_id', v_room.active_lesson_id,
    'expires_at', v_room.expires_at
  );
end;
$$;

create function public.update_live_board_student(
  p_room_code text,
  p_student_token text,
  p_expected_revision bigint,
  p_fen text,
  p_pgn text,
  p_last_move jsonb
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_room public.live_board_rooms;
  v_hash text;
begin
  v_hash := encode(extensions.digest(convert_to(coalesce(p_student_token, ''), 'UTF8'), 'sha256'), 'hex');

  update public.live_board_rooms
  set fen = p_fen,
      pgn = coalesce(p_pgn, ''),
      last_move = p_last_move,
      revision = revision + 1,
      updated_at = now(),
      expires_at = greatest(expires_at, now() + interval '12 hours')
  where room_code = p_room_code
    and (student_token_hash = v_hash or student_short_token_hash = v_hash)
    and expires_at > now()
    and student_moves_allowed
    and revision = p_expected_revision
  returning * into v_room;

  if not found then
    raise exception 'Student move rejected because the room is locked, stale, or access is invalid';
  end if;

  return jsonb_build_object(
    'room_code', v_room.room_code,
    'fen', v_room.fen,
    'pgn', v_room.pgn,
    'orientation', v_room.orientation,
    'last_move', v_room.last_move,
    'student_moves_allowed', v_room.student_moves_allowed,
    'revision', v_room.revision,
    'active_lesson_id', v_room.active_lesson_id,
    'expires_at', v_room.expires_at
  );
end;
$$;

-- Session message functions ---------------------------------------------------

create function public.get_live_board_messages(
  p_room_code text,
  p_access_token text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
stable
as $$
declare
  v_hash text;
begin
  v_hash := encode(extensions.digest(convert_to(coalesce(p_access_token, ''), 'UTF8'), 'sha256'), 'hex');

  if not exists (
    select 1
    from public.live_board_rooms
    where room_code = p_room_code
      and expires_at > now()
      and (teacher_token_hash = v_hash
           or student_token_hash = v_hash
           or student_short_token_hash = v_hash)
  ) then
    raise exception 'Room not found or access token is invalid';
  end if;

  return (
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', m.id,
          'sender_role', m.sender_role,
          'created_at', m.created_at,
          'body', m.body
        )
        order by m.created_at, m.id
      ),
      '[]'::jsonb
    )
    from (
      select id, sender_role, created_at, body
      from public.live_board_messages
      where room_code = p_room_code
      order by created_at desc, id desc
      limit 200
    ) m
  );
end;
$$;

create function public.post_live_board_message(
  p_room_code text,
  p_access_token text,
  p_body text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_room public.live_board_rooms;
  v_message public.live_board_messages;
  v_hash text;
  v_role text;
  v_body text;
begin
  v_hash := encode(extensions.digest(convert_to(coalesce(p_access_token, ''), 'UTF8'), 'sha256'), 'hex');
  v_body := btrim(coalesce(p_body, ''));

  if char_length(v_body) not between 1 and 500 then
    raise exception 'Message body must be between 1 and 500 characters';
  end if;

  select * into v_room
  from public.live_board_rooms
  where room_code = p_room_code
    and expires_at > now();

  if not found then
    raise exception 'Room not found or access token is invalid';
  end if;

  -- Sender role is derived from the token, never supplied by the client, so
  -- a student token cannot post as the coach.
  if v_room.teacher_token_hash = v_hash then
    v_role := 'teacher';
  elsif v_room.student_token_hash = v_hash or v_room.student_short_token_hash = v_hash then
    v_role := 'student';
  else
    raise exception 'Room not found or access token is invalid';
  end if;

  insert into public.live_board_messages (room_code, sender_role, body)
  values (p_room_code, v_role, v_body)
  returning * into v_message;

  -- Chat counts as room activity, same as board updates.
  update public.live_board_rooms
  set expires_at = greatest(expires_at, now() + interval '12 hours')
  where room_code = p_room_code;

  -- Bound retained history per room.
  delete from public.live_board_messages
  where room_code = p_room_code
    and id not in (
      select id
      from public.live_board_messages
      where room_code = p_room_code
      order by created_at desc, id desc
      limit 500
    );

  return jsonb_build_object(
    'id', v_message.id,
    'room_code', v_message.room_code,
    'sender_role', v_message.sender_role,
    'created_at', v_message.created_at,
    'body', v_message.body
  );
end;
$$;

create function public.clear_live_board_messages(
  p_room_code text,
  p_teacher_token text
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $$
declare
  v_hash text;
begin
  v_hash := encode(extensions.digest(convert_to(coalesce(p_teacher_token, ''), 'UTF8'), 'sha256'), 'hex');

  if not exists (
    select 1
    from public.live_board_rooms
    where room_code = p_room_code
      and teacher_token_hash = v_hash
      and expires_at > now()
  ) then
    raise exception 'Room not found or access token is invalid';
  end if;

  delete from public.live_board_messages where room_code = p_room_code;

  return jsonb_build_object('cleared', true);
end;
$$;

-- Grants ----------------------------------------------------------------------

revoke all on function public.create_live_board_room(text, text, text, text, text, text) from public;
revoke all on function public.create_live_board_room_v2(text, text, text, text, text, text, text) from public;
revoke all on function public.get_live_board_room(text, text) from public;
revoke all on function public.update_live_board_student(text, text, bigint, text, text, jsonb) from public;
revoke all on function public.get_live_board_messages(text, text) from public;
revoke all on function public.post_live_board_message(text, text, text) from public;
revoke all on function public.clear_live_board_messages(text, text) from public;

grant execute on function public.create_live_board_room(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.create_live_board_room_v2(text, text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_live_board_room(text, text) to anon, authenticated;
grant execute on function public.update_live_board_student(text, text, bigint, text, text, jsonb) to anon, authenticated;
grant execute on function public.get_live_board_messages(text, text) to anon, authenticated;
grant execute on function public.post_live_board_message(text, text, text) to anon, authenticated;
grant execute on function public.clear_live_board_messages(text, text) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
